language: node_js
node_js:
  - 16

cache: npm

before_install:
  - cd project
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: project/dist
  on:
    branch: main
