language: node_js
node_js:
  - "node"

cache: npm

script: cd project && npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: project/dist
  on:
    branch: main